name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Runs on GitHub's macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake ninja  # Install necessary tools
              
      - name: Install dependencies
        run: brew install libomp
        
      - name: Extract After Effects SDK
        run: |
          unzip -o May2023_AfterEffectsSDK_Win.zip

      - name: Configure build
        run: |
          cmake -B build -S . -G "Ninja" \
          -DCMAKE_CXX_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
          -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix libomp)/lib -lomp"
        env:
          AE_SDK_PATH: $GITHUB_WORKSPACE


      - name: Compile code
        run: cmake --build build
        
