name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Runs on GitHub's macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake ninja llvm libomp  # Install all dependencies at once

      - name: Extract After Effects SDK
        run: unzip -o May2023_AfterEffectsSDK_Win.zip

      - name: Configure build
        run: |
          export PATH="$(brew --prefix llvm)/bin:$PATH"
          export CC="$(brew --prefix llvm)/bin/clang"
          export CXX="$(brew --prefix llvm)/bin/clang++"
          
          cmake -B build -S . -G "Ninja" \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_CXX_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix libomp)/lib -lomp"
        env:
          AE_SDK_PATH: $GITHUB_WORKSPACE

      - name: Compile code
        run: cmake --build build

